fix the issue #103 by create two new FastCloners
kostaskougios/cloning pull request #109
Opened 2021-07-23 07:09 UTC by ZhenXiongQian

To fix issue [#103 ](https://github.com/kostaskougios/cloning/issues/103)
In jdk 5, `cloner.deepClone(Set.of(1)).size()` will be 2 because `EMPTY`( it is `null` in jdk14 ) will be changed with clone. So it has to create new FastCloner.

2021-07-23 11:06 UTC, tweimer requested changes
That is wrong, you must also clone the elements of the lists.

2021-07-24 01:09 UTC, ZhenXiongQian commented
ok, I change the code to use cloner.deepClone

2021-07-31 01:33 UTC, ZhenXiongQian commented
@tweimer is this pr ok now？

2021-07-31 09:26 UTC, tweimer commented
See my comment in the review. A test for List.of with two elements would be useful,for the sake of completeness.

2021-08-03 06:44 UTC, ZhenXiongQian commented
the test cases are now complete

2021-08-03 06:53 UTC, tweimer commented
Like good to me.

@kostaskougios has to merge it

2021-08-03 06:53 UTC, tweimer approved these changes

2021-08-04 10:47 UTC, kostaskougios approved these changes

2021-08-04 10:48 UTC, merged

2021-08-04 10:54 UTC, kostaskougios commented
:+1:

2021-09-10 08:10 UTC, chadlwilson commented
Assuming you feel this is stable at this stage, any chance of cutting another release @kostaskougios and @tweimer ?

2022-04-05 22:19 UTC, atribemc commented
Any chance 1.11.0 making it to maven central so i can get this fix?

2022-04-05 22:59 UTC, chadlwilson commented
@atribemc Seems unlikely based on https://github.com/kostaskougios/cloning/issues/105#issuecomment-978225059

I did start to consider maintaining/releasing a fork at https://github.com/chadlwilson/cloning but haven't pushed it anywhere yet/set up automation, as for my use case we had our own fast cloners for the issue in this PR and we needed `--add-opens` anyway making the other unreleased Java 16 fixes not so relevant.

I'm not sure if any other possible fork candidates have emerged...